metagenlab/zDB

.gitignore, annotation_pipeline.nf, bin/setup_chlamdb.py, bin/zdb, nextflow.config, webapp/chlamdb/views.py, webapp/manage.py, webapp/templates/chlamdb/locus.html, webapp/templates/chlamdb/og.html, zdb/database/database.py
With this PR we add a pipeline to extract AMR annotations using the [AMRFinderPlus](https://www.ncbi.nlm.nih.gov/pathogens/antimicrobial-resistance/AMRFinder/) software and add them to the database. I also added the annotations to the locus and orthogroup views.
Also note that:
- currently only docker is supported, will add conda support later.
- I had to fix a few f-strings that got broken by autopep8. It seems that pycodestyle does not correctly support f-strings.
Screenshot of the annotations on a locus tag view
=> Add antimicrobial resistance annotations 

.gitignore, README.md, annotation_pipeline.nf, conda/testing.yaml, db_setup.nf, docs/CHANGELOG.md, nextflow.config, testing/base.py, testing/pipelines/assets/R6724_16313_small.gbk, testing/pipelines/assets/R6726_16314_small.gbk, testing/pipelines/assets/R6728_16315_small.gbk, testing/pipelines/assets/test_input.csv, testing/pipelines/test_annotation_pipeline.py, testing/pipelines/test_db_setup.py
With this PR we port the nextflow pipelines to the DSL2 language. To avoid braking anything I've also added a series of unitests for the pipelines.
=> Port nextflow pipelines to DSL2 language.

docs/CHANGELOG.md, webapp/chlamdb/views.py, webapp/templates/chlamdb/extract_nav_tabs_template.html, webapp/templates/chlamdb/tabular_comparison.html
Navigation tabs were broken for the orthogroup comparison view. While I was at it I cleaned-up two more html templates to make them more readable (just fixed the indentations).
=> Fix orthogroup comparison view navigation tabs.

.readthedocs.yaml, README.md, docs/CHANGELOG.md, docs/requirements.txt
This PR allows us to build the [documentation](https://zdb.readthedocs.io/en/latest/) from this repository instead of from the chlamdb repository.
I tested it by switching the "latest" build to this repository. I had to duplicate this branch to the `blast_merge` branch and [use that to build the documentation](https://readthedocs.org/dashboard/zdb/advanced/), as I can't update the list of branches available on readthedocs (if I understood, a webhook is needed for that, but I don't have the permissions to set that up).
=> Add configuration for readthedocs

docs/CHANGELOG.md, testing/webapp/test_views.py, webapp/chlamdb/urls.py, webapp/lib/db_utils.py, webapp/templates/chlamdb/fam.html, webapp/views/entry_lists.py, webapp/views/hits_extraction.py, webapp/views/utils.py, webapp/views/venn.py, webapp/views/views.py
We add a details view (`fam_amr`) for AMR genes. These views (`fam_cog`, `fam_ko`, `fam_pfam`) already share a single template. It also seems that these views share a lot of code but I did not take the time to refactor them as class-based views to avoid code repetition.
=> Add fam_amr view (AMR gene details view)

docs/CHANGELOG.md, testing/webapp/test_views.py, webapp/templates/chlamdb/extract_nav_tabs_template.html, webapp/templates/chlamdb/plot_heatmap.html, webapp/views/utils.py, webapp/views/views.py
In this PR we add the heatmap view for AMR genes. Not that the view fails on the testing dataset, as there are not enough hits leading to an empty distance matrix.
=> Add plot_heatmap view for AMR genes.

docs/CHANGELOG.md, testing/webapp/test_views.py, webapp/templates/chlamdb/extract_nav_tabs_template.html, webapp/templates/chlamdb/pan_genome.html, webapp/views/utils.py, webapp/views/views.py
In this PR I add the AMR accumulation/rarefaction plot view.
=> Add AMR accumulation/rarefaction plot view.

annotation_pipeline.nf, bin/setup_chlamdb.py, conda/amrfinderplus.yaml, db_setup.nf, docs/CHANGELOG.md, nextflow.config, testing/pipelines/test_annotation_pipeline.py, testing/pipelines/test_db_setup.py, utils/setup_base_db.py, webapp/assets/bibliography/references.bib, webapp/lib/db_utils.py, webapp/templates/chlamdb/home.html, webapp/views/views.py
With this PR we add a new "versions" table to the database and store the versions of the different reference databases used as well as of the AMRFinderPlus software in it. We display that information on the home page of zDB.
=> Add reference DB and software versions to database.

annotation_pipeline.nf, bin/setup_chlamdb.py, bin/zdb, conda/annotation.yaml, db_setup.nf, docs/CHANGELOG.md, nextflow.config, testing/pipelines/test_annotation_pipeline.py, testing/pipelines/test_db_setup.py, utils/setup_base_db.py, webapp/lib/db_utils.py
With this PR I add option to download the VFDB (http://www.mgc.ac.cn/VFs/) and blast against it.
I've created a new docker image for the annotation container (see https://github.com/metagenlab/docker-images/pull/2)
=> Add virulence factor annotations.

annotation_pipeline.nf, bin/setup_chlamdb.py, bin/zdb, db_setup.nf, docs/CHANGELOG.md, nextflow.config, testing/pipelines/test_annotation_pipeline.py, testing/webapp/test_views.py, utils/setup_base_db.py, webapp/chlamdb/forms.py, webapp/chlamdb/urls.py, webapp/lib/db_utils.py, webapp/lib/queries.py, webapp/templates/chlamdb/entry_list.html, webapp/templates/chlamdb/extract_nav_tabs_template.html, webapp/templates/chlamdb/home.html, webapp/templates/chlamdb/menu.html, webapp/views/entry_lists.py, webapp/views/fam.py, webapp/views/hits_extraction.py, webapp/views/mixins.py, webapp/views/tabular_comparison.py, webapp/views/utils.py, webapp/views/venn.py, webapp/views/views.py
With this pull request we add all the standard views for the virulence factors, i.e.
- detail view
- comparison index view
- entry list
- tabular comparison
- Venn diagram
- presence/absence table
- heatmap
- accumulation/rarefaction plot
=> Add all the standard views for the virulence factors

docs/CHANGELOG.md, testing/webapp/test_views.py, webapp/templates/chlamdb/blast.html, webapp/views/views.py
Blast view was broken because of two things:
- [ Fix of mixup in the annotation pipeline between ffn and fna databases](https://github.com/metagenlab/zDB/pull/17/files#diff-440f682582f0857326c90c97e62e794a581bd01b8c2711f9120e34b96177688cR2862) got [partially overwritten in a subsequent PR](https://github.com/metagenlab/zDB/commit/571c162a7f77d33b9daad1199768515ac8b613cf#diff-440f682582f0857326c90c97e62e794a581bd01b8c2711f9120e34b96177688cR2887), probably because of some rebase fail.
- A template that got deleted was being used by the view, but it was unnecessary as it actually never generated the venn diagram.
=> Fix blast view

bin/zdb, db_setup.nf, nextflow.config
As we blast protein sequences against the VFDB we now download the protein database instead of the nucleotide database.
=> Fix blast against the VFDB.

webapp/templates/chlamdb/index_comp.html
Because of a missing space the static icons had a trailing "/", which prevented them from being found in a productive setup.
=> Fix icons in comparison index views.

annotation_pipeline.nf, bin/setup_chlamdb.py, conda/annotation.yaml, conda/testing.yaml, conda/webapp.yaml, docs/CHANGELOG.md, nextflow.config, testing/pipelines/test_annotation_pipeline.py, testing/webapp/test_views.py, webapp/lib/db_utils.py
We can use the `-max_hsps 1` option to limit search results as it will return the best (lowest evalue) hit for each subject/query pair. As we only want to keep one hit per locus, we further filter the results before uploading to the DB.
=> Filter VF hits by SeqID and coverage and keep one hit per locus.

webapp/templates/chlamdb/home.html, webapp/views/views.py
Seems I broke the home view for cases there not all optional annotations are present and there was an error in the display of orthogroups and KOs
=> Fix home view for DBs with missing optional annotations.

webapp/lib/ete_phylo.py
because of a trailing coma, face_params were defined as a tuple in ValueColoredColumn, which breaks various views. This used to work as face_params were simply always ignored before.
=> Fix bug in ValueColoredColumn.

annotation_pipeline.nf, bin/annotations.py, bin/setup_chlamdb.py, docs/CHANGELOG.md, testing/pipelines/assets/test_input.csv, testing/pipelines/base.py, testing/pipelines/test_annotation_pipeline.py, testing/pipelines/test_annotations_functional.py, testing/pipelines/test_db_setup.py, testing/webapp/test_views.py, webapp/assets/css/style_FILE_zDB.css, webapp/chlamdb/forms.py, webapp/lib/db_utils.py, webapp/views/gwas.py
With this PR we introduce the possibility of defining groups of genomes. 
For now the groups can only be defined in the input CSV file and they can only be used in the GWAS view. 
Also note that we are no longer handling errors ourselves in the GWAS view, but let django forms take care of error handling. This has the advantage that field validation errors will get displayed on that particular field in the form, whereas other form validation errors (e.g. depending on several fields) will be displayed at the top of the form, as seen in the screenshots below. I plan on refactoring all forms in the future to apply this approach.
I will continue to work on this feature in future commits, notably to enable the use of the groups in other views, add the possibility to add and edit groups and add …
=> Allow defining groups of genomes in input file.

docs/CHANGELOG.md, webapp/assets/css/style_FILE_zDB.css, webapp/assets/js/genomic_region.js, webapp/chlamdb/forms.py, webapp/lib/db_utils.py, webapp/templates/chlamdb/blast.html, webapp/templates/chlamdb/plot_region.html, webapp/views/custom_plots.py, webapp/views/errors.py, webapp/views/gwas.py, webapp/views/hits_extraction.py, webapp/views/utils.py, webapp/views/venn.py, webapp/views/views.py
Instead of doing custom error handling in the forms, we now use the default django forms behavior. This is much better as the errors get displayed next to the corresponding fields whenever possible, i.e. when validation fails for a specific field, the error will get displayed there, for other errors, we end up with an error message in a banner above the form, as we had before. See screenshot below and screenshots in https://github.com/metagenlab/zDB/pull/82 for more examples.
We also add more error handling for the custom plots view and improve the blast view notably by displaying the help as to what is expected in the "blast input" field as a placeholder in the `TextArea` widget.
=> Display form validation errors next to the corresponding fields.

docs/CHANGELOG.md, testing/webapp/test_views.py, webapp/chlamdb/forms.py, webapp/views/utils.py
With this PR we now allow selecting groups in the forms wherever pertinent, notably in all the comparison views and the plot region view.
Of note is that we lost the "all" and "None" buttons in the process, which are not built-in with select2 and not that easy to implement with choices being fetched with asynchronous requests. I think this is OK though as groups allow for easy selection and I will implement group management next.
=> Handle groups when selecting genomes wherever pertinent.

conda/webapp.yaml
On Mac gxx is already installed and should not be in the requirements.
=> Fix webapp conda environment for macOS.

docs/CHANGELOG.md, webapp/assets/css/style_FILE_zDB.css, webapp/templates/chlamdb/entry_list.html, webapp/templates/chlamdb/extract_hits.html, webapp/templates/chlamdb/extract_hits_details_table.html, webapp/templates/chlamdb/extract_hits_results_table.html, webapp/templates/chlamdb/header.html, webapp/templates/chlamdb/result_table.html, webapp/templates/chlamdb/tabular_comparison.html, webapp/views/gwas.py, webapp/views/utils.py
With this PR we add a checkbox column to most data tables, allowing the selection of rows. We also include a select all button. The selection is used to limit table exports to the selected data.
=> Control data exports from tables by making rows selectable.

docs/CHANGELOG.md, testing/webapp/test_utils.py, webapp/views/utils.py
`group_0`  was not correctly mapped back to the orthogroup with ID 0, leading to issues for example when selecting that group for a custom phylogeny plot.
=> Correctly handle group_0 in EntryIdParser.

docs/CHANGELOG.md, webapp/lib/db_utils.py, webapp/views/views.py
With this PR we fix various bugs in views that fail when there are no gene annotations. Indeed we had cases where the `gene` column was entirely missing in the `dataframe` because it did not appear in any of the query results, which led to failing views. We fix that case for
- `search_bar` results
- `extract_contigs` view
- `locusx` view
=> Fix various views for cases where there are no gene annotations.

docs/CHANGELOG.md, webapp/views/gwas.py
Scoary-2 uses a database to store scores for topologies and it caches the connection and cursor to that database when scoary gets loaded. This leads to issues for the integration as the SQL object might be used in a different thread than it was created in. We fix it here by resetting the connection before calling scoary.
Note that I have also opened [a PR in the scoary repo](https://github.com/MrTomRod/scoary-2/pull/13), so the current fix would not be necessary anymore if it gets fixed there and a new release is made...
=> Fix Scoary-2 integration.

docs/CHANGELOG.md, webapp/views/mixins.py, webapp/views/utils.py
We also improve formatting of lists to html (such as for products, genes, functions, etc.). See screenshots below for both fixes:
**before fix, products are screwed up and - appear in the middle of the lists**
**after fix, everything is neat**
=> Fix product representation in GWAS view for orthogroups.

bin/setup_chlamdb.py, conda/annotation.yaml, conda/webapp.yaml, docs/CHANGELOG.md, webapp/lib/db_utils.py
Filtering of COGs in the annotation pipeline was actually picking the hits with lowest target sequence id, i.e. random ones, instead of the best ones. We now instead pick the hits with lowest E-value and highest sequence identity.
We also fix a small bug that was introduced with https://github.com/metagenlab/zDB/pull/99 and we fix some conda environment issues.
=> Fix filtering of COGs in annotation pipeline.

CHANGELOG.md, bin/zdb
When running with singularity the current working directory and home folders get mounted by default. It seems that this can collide with our own mounts, which get mounted into webapp/assets of the zDB directory, which usually also is the CWD. I did not quite understand why this works in certain cases but not in others, but it seems this led to zDB not running with singularity on our server. Adding the -c option to avoid sharing the filesystem resolves this issue.
=> Fix binding of folders when running with singularity.

CHANGELOG.md
We move some entries in the changelog to release 1.3.1 from 1.3.0, as we had moved the 1.3.0 tag but had to move it back (see discussion https://github.com/bioconda/bioconda-recipes/pull/49199/). 
So the release 1.3.0 is basically broken.
=> Update changelog to prepare release 1.3.1.

CHANGELOG.md, annotation_pipeline.nf
Config-defined parameters using interpolated strings are no longer cast to `Strings` since nextflow version 24.03. We therefore need to check for `GStrings` ourselves and cast them to Strings.
This issue was reported in https://github.com/nextflow-io/nextflow/issues/4944, and it was fixed in the sense that `GStrings` from the config file behave correctly, but they are still `GStrings` in newer version of nextflow.
=> Fix annotation pipeline for nextflow version > 24.03.

CHANGELOG.md, README.md, conda/checkm.yaml, conda/testing.yaml, testing/conda/test_environments.py
The `checkm` conda environment was broken. Somehow the latest version of `checkm` has dependencies that are not found in the `bioconda` channel, we therefore need to add the `conda-forge` channel. Moreover `checkm` is broken for newer versions of python which do not incorporate setuptools, so we add that as a dependency as well.
We also add a new test suite, testing that all environments work and update the release process in the README accordingly.
=> Update conda environments

.gitignore, CHANGELOG.md, bin/zdb, testing/webapp/test_views.py, webapp/settings/settings.py, webapp/settings/testing_settings.py, webapp/start_webapp, webapp/views/custom_plots.py, webapp/views/fam.py, webapp/views/gwas.py, webapp/views/locus.py, webapp/views/views.py
The dal and dal_select2 apps come with static files which need to be served. This is done automatically when running the dev_server but not when using nginx and gunicorn. In that case we need to use the collectstatic command to gather all the necessary static files into one folder and then serve that folder.
We also improve cleaning-up of the files when the webapp gets shut-down, which is mainly an issue with docker as folders and files get created by root, leading to issues when running with conda or singularity after running with docker.
_Describe the changes and add screenshots when pertinent as visual help._
=> Add missing assets when running webapp with nginx and gunicorn.

CHANGELOG.md, webapp/assets/css/style_FILE_zDB.css, webapp/chlamdb/forms.py, webapp/templates/chlamdb/kegg.html, webapp/views/views.py
Selection with the autocomplete widget was not working for the kegg-based comparative analysis form. We have fixed this by using crispy forms to render the forms on the kegg-based view. We have also improved the overall layout and style of the view as shown in the screenshots below.
**Kegg based view before fix**
**Kegg based view after fix**
=> Fix kegg forms

README.md
conda-forge channel is needed to install the more recent versions of zDB as they depend on mamba (since v 1.2.1 build 1)
=> Update README with up to date installation information.

CHANGELOG.md, webapp/chlamdb/forms.py, webapp/lib/ete_phylo.py, webapp/views/custom_plots.py
With this PR we add the possibility to highlight specific entries in custom phylogenetic trees. See screenshot below:
Closes #127
=> Add option to highlight certain leaves in custom plots.

CHANGELOG.md, webapp/templates/chlamdb/venn_representation_template.html
Not all numbers are displayed in the classic representation for the venn diagram with 6 genomes. Adding all numbers makes the diagram unreadable (see screenshot below). Instead we now display it as Edwards. This is a bit of a cheap fix, but the only other option would be to replace the library generating the venn diagrams. We should maybe do that at some point as the current library is really bad, with no option to change the size of the figure and such. Everything is hard coded in the javascript library (position and shapes of everything).
**Classic representation with all numbers**
**Edwards representation**
resolves #132
=> Display Venn diagram as Edwards for 6 genomes

CHANGELOG.md, webapp/views/utils.py, webapp/views/views.py
We automatically determine the best order to display the regions in the plot_region view, maximizing the number and order of common orthogroups between consecutive regions. Note that we use a local optimum, taking a path of maximum score between neighbouring regions, not over the full path (although we take the best path among such paths obtained for all starting regions).
As an example see the two screenshots of the same genomic region, with the ordered optimized or not. Note that with the optimization of the order of display of the regions, it is clear in that case that there are 2 orientations for the genes in the region. The homology between certain regions is also much clearer, as prior to optimization a region which does not conserve the OGs is placed in the in the second row.
We …
=> Optimize order of regions in plot_region.

CHANGELOG.md, bin/setup_chlamdb.py, conda/amrfinderplus.yaml, nextflow.config
The output of AMRFinder has changed in release 4, so we need to update our code accordingly. This means that zDB only works with AMRFinder 4 or above. We also pin the container to the latest version of AMRFinder and update the conda environment to make sure to use AMRFinder version 4.
see https://github.com/evolarjun/amr/wiki/New-in-AMRFinderPlus/#amrfinderplus-40 for changes to the AMRFinder output.
=> Support for AMRFinder version 4

CHANGELOG.md, README.md, db_setup.nf, testing/pipelines/test_db_setup.py
Tests were failing as the reference database gets written to a temporary directory in `/tmp/xyz`, which is not accessible from within the container, so all the statements moving files to that location were actually moving them to that path in the container. We now exclusively use nextflow's publishing mechanism, which is anyway much cleaner.
=> Fix reference database pipeline

CHANGELOG.md, bin/zdb, webapp/settings/settings.py, webapp/start_webapp
It seems that the CSRF protection has changed in django 4.0 and it is now necessary to set the trusted origins in certain situations. See
https://docs.djangoproject.com/en/5.1/releases/4.0/#csrf-trusted-origins-changes
We notably need to set the `CSRF_TRUSTED_ORIGINS` for our demo zdb.metagenlab.ch.
=> Add command line parameter to set CSRF_TRUSTED_ORIGINS.

CHANGELOG.md, webapp/assets/bibliography/references.bib, webapp/templates/chlamdb/credits.html, webapp/templates/chlamdb/home.html
Home page was still citing the ChlamDB paper and the about page was not showing any reference to zDB or ChlamDB.
=> Cite zDB paper on home page and about pages.

CHANGELOG.md, utils/export_loci_annotations.py
The script allows to export lists of Loci with their KO and COG annotations. These can be used as input for our rnaseq pipeline (https://github.com/metagenlab/rnaseq).
=> Add script to export loci annotation tables.

CHANGELOG.md, webapp/views/locus.py
Some contigs have several accessions which broke the representation of the accession. We could have fixed it to display all accessions associated with a contig, but I do not see the point, so instead we just show the one from the bioentry table.
**Before**
**After**
=> Fix accession in contig tab of locusx view.

CHANGELOG.md, annotation_pipeline.nf, bin/setup_chlamdb.py, bin/zdb, conda/islandpath.yaml, nextflow.config, utils/setup_base_db.py, webapp/assets/css/style_FILE_zDB.css, webapp/chlamdb/urls.py, webapp/lib/db_utils.py, webapp/lib/queries.py, webapp/templates/chlamdb/genomic_island.html, webapp/templates/chlamdb/home.html, webapp/templates/chlamdb/locus.html, webapp/views/analysis_view_metadata.py, webapp/views/entry_lists.py, webapp/views/genomic_island.py, webapp/views/locus.py, webapp/views/mixins.py, webapp/views/object_type_metadata.py, webapp/views/utils.py, webapp/views/views.py
With this PR we:
- Integrate `island_path` into the annotation pipeline.
- Add information about containing genomic islands to the `locusx` view.
- Add a detail view for genomic islands.
- Add the entry list view for genomic islands
This is a rough first step, but there is much more work to be done in order to properly integrate genomic islands into zDB, notably:
- Cluster homologous genomic islands together
- Display clusters of genomic islands with similarity between them
- Show lists of genes in a given genomic island
- Presence/absence table of genomic islands in various genomes
- ...
=> Add genomic island predictions and views

CHANGELOG.md, annotation_pipeline.nf, db_setup.nf, nextflow.config
Make sure zDB modules are importable in annotation container.
By default both docker and singularity mount the `$home` folder, which usually contains the conda packages and hence zDB. So this was actually working most of the time, but not on Obelix, where we have a common conda installation for all users, therefore outside of their home folder. Import of the zDB libraries would therefore raise errors on obelix. With this PR, we make sure to mount the zDB folder into the containers whenever necessary.
=> Fix import errors in pipelines when using docker or singularity.

CHANGELOG.md, webapp/views/views.py
The circos view was raising an error because of a drop_duplicates on a nonexistent "index" column.
=> fix drop_duplicates on nonexistent column in circos view

CHANGELOG.md, webapp/templates/chlamdb/locus.html
Seems I forgot to adapt the locus view when I renamed the option in `optional2status`...
=> Fix displaying genomic islands in locus view.

CHANGELOG.md, testing/pipelines/test_annotation_pipeline.py, testing/webapp/test_views.py, webapp/chlamdb/urls.py, webapp/lib/db_utils.py, webapp/lib/queries.py, webapp/templates/chlamdb/fam.html, webapp/templates/chlamdb/fam_general_tab.html, webapp/templates/chlamdb/genomic_island.html, webapp/templates/chlamdb/home.html, webapp/templates/chlamdb/plot_region.html, webapp/templates/chlamdb/region.html, webapp/views/analysis_view_metadata.py, webapp/views/fam.py, webapp/views/genomic_island.py, webapp/views/hits_extraction.py, webapp/views/locus.py, webapp/views/mixins.py, webapp/views/object_type_metadata.py, webapp/views/tabular_comparison.py, webapp/views/utils.py, webapp/views/venn.py, webapp/views/views.py
With this PR we add the visualizations of genomic island clusters. Notably:
- The comparison views for genomic island clusters (index, extraction form, venn, presence/absence table, heatmap, accumulation/rarefaction)
- A details view for genomic islands
- A details view for genomic island clusters
For the genomic island cluster details view we use the fam view, so that we display 3 tabs. A tab with general information, a tab with the list of GIs in that cluster and a tab with the phylogenetic distribution of the cluster.
In the general tab we also show the genomic regions of all the GIs in the cluster.
We still have an issue with genomic islands in circular contigs spanning the "end" of the contig. Will fix that in a separate PR.
=> Add genomic island cluster visualisations and comparison views

bin/setup_chlamdb.py, webapp/lib/db_utils.py, webapp/lib/queries.py, webapp/views/fam.py, webapp/views/genomic_island.py
We actually do not need this, as islandpath does not predict GIs spanning the end of a contig. This was a side-effect of using islandpath on genomes with several contigs, which is not supported by the software. To avoid this issue we will instead run islandpath on each contig in a future PR.
=> Revert handling of GI spanning end of circular contig

CHANGELOG.md, webapp/assets/js/genomic_region.js, webapp/views/mixins.py, webapp/views/views.py
In this PR we fix a few bugs for the display of the genomic islands notably for the plot of the genomic regions:
- Fix optimization of orientation of genomic regions.
- Fix choosing the optimal order of genomic regions.
- Improve score for optimal ordering of genomic regions.
- Add length to genomic island table.
- Fix relative sizes of plotted regions.
- Fix bug in `genomic_region.js` for very small regions.
=> Improve display of genomic islands

CHANGELOG.md, webapp/assets/js/genomic_region.js, webapp/lib/db_utils.py, webapp/lib/queries.py, webapp/templates/chlamdb/genomic_island.html, webapp/templates/chlamdb/locus.html, webapp/templates/chlamdb/region.html, webapp/views/fam.py, webapp/views/genomic_island.py, webapp/views/views.py
With this PR we add coloring of AMR and VF genes in genomic representations of GIs and GI clusters.
To do so, we make the `to_highlight` parameter into a dictionary instead of a list, allowing to set the color for individual loci directly in python.
=> Highlight AMR and VF genes in genomic island representations.

CHANGELOG.md, webapp/lib/queries.py
We were displaying the GI cluster ID in the locus view, but linking it as if it were a GI. We now correctly display the link to the GI.
=> Display correct GI ID in locus view.

CHANGELOG.md, annotation_pipeline.nf
Cleanup basically only worked for .gbk and .gbff inputs. We now support any extension.
resolves #179
=> Fix annotation pipeline for input file with .genbank extensions.

CHANGELOG.md, annotation_pipeline.nf, bin/zdb, conda/orthofinder.yaml, nextflow.config, testing/pipelines/assets/R6724_16313_small.gbk, testing/pipelines/test_annotation_pipeline.py, webapp/assets/bibliography/references.bib
In this PR we update orthofinder to version 3.1, which allows to calculate the orthogroup without an all vs all alignment. This is achieved by doing an all vs all for a subset of the genomes, determining the OGs and then adding subsequent genomes by aligning against those OGs (new OGs are still added whenever necessary), see https://github.com/OrthoFinder/OrthoFinder for more information.
Below a table showing the duration of the analysis pipeline with orthofinder 2 and orthofinder 3 run on obelix on 30 cores, without any extra optional annotations.
|Genomes | Orthofinder 2| Orthofinder 3|
|---------------|--------------------|---------------------|
|   10           |   0:18              |         0:19          |
|   50           |    1:55             |        1:08           |
|   100 …
=> Update orthofinder to version 3 to improve scaling of analysis pipeline

CHANGELOG.md, testing/webapp/test_autocomplete_views.py, testing/webapp/test_utils.py, webapp/lib/queries.py, webapp/templates/chlamdb/circos.html, webapp/views/circos.py
With this pull request we further improve the circos view. Specifically we:
- Add a track for the genomic islands
- Allow displaying VFs and AMRs on the reference genome. This is done by allowing to switch between different color schemes for the reference genome.
- Allow hiding/showing certain tracks on the circos map.
- Overall improvement of the map by improving spacing, colors and legend order.
=> Add possibility to display GIs, AMRs and VFs and to show/hide certain tracks on circos map

CHANGELOG.md, webapp/templates/chlamdb/extract_hits.html
We move the circos form next to the result interpretation help box.
Before the the results would look like this (depending on screen width), with the form relegating the results to very low on the page and also the form not clearly marked as such:
Now it's more compact and the form is better isolated. Also I added a label to the field for selecting the reference genome.
=> Improve styling of extraction view.
