metagenlab/zDB

- annotation_pipeline.nf
- bin/annotations.py
- bin/setup_chlamdb.py
- db_setup.nf
> Add gaps when missing core orthogroups

- conda/annotation.yaml
- conda/testing.yaml
- conda/webapp.yaml
- webapp/lib/db_utils.py
SeqUtils.GC does not exist anymore in biopython 1.8.
> Use biopython version 1.8 and higher.

- webapp/lib/db_utils.py
> Make db_utils.py PEP8 compliant.

- webapp/templates/chlamdb/fam.html
- webapp/views/utils.py
Link was escaped, so non functional in the AMR details view.
> Fix hmm link representation in AMR details view.

- utils/setup_base_db.py
Main changes are
- Add the missing settings in the DB
- Modify the script to avoid downloading all KOs
> Update and speed-up base DB setup script.

- annotation_pipeline.nf
- bin/setup_chlamdb.py
- conda/kofamscan.yaml
With this PR we fix two bugs with conda environments (kofamscan environment did not build anymore and when using conda, we need to make sure to that the amr database is downloaded before searching for AMRs.)
> Various small bug fixes

- webapp/chlamdb/forms.py
- webapp/templates/chlamdb/gwas.html
- webapp/views/gwas.py
With this PR we add a form allowing to set the `q-value` cutoff, upload a phenotype file and limit the number of hits for GWAS analyses.
> Add specific form for GWAS analysis.

- testing/pipelines/test_annotation_pipeline.py
As blast against the VFDB was fixed [in a previous PR](https://github.com/metagenlab/zDB/pull/65), we now have many more hits in our testing database.
_Describe the changes and add screenshots when pertinent as visual help._
> Update annotation pipeline tests for VFs.

- utils/time_views.py
- webapp/lib/queries.py
The query was unnecessarily complicated...
> Speedup VF query

- testing/webapp/test_views.py
- webapp/chlamdb/forms.py
- webapp/templates/chlamdb/cog_barplot.html
- webapp/templates/chlamdb/cog_phylo_heatmap.html
- webapp/templates/chlamdb/comparison_header.html
- webapp/templates/chlamdb/entry_list.html
- webapp/templates/chlamdb/extract_hits.html
- webapp/templates/chlamdb/gwas.html
- webapp/templates/chlamdb/home.html
- webapp/templates/chlamdb/ko_barplot.html
- webapp/templates/chlamdb/menu.html
- webapp/templates/chlamdb/pan_genome.html
- webapp/templates/chlamdb/plot_heatmap.html
- webapp/templates/chlamdb/tabular_comparison.html
- webapp/templates/chlamdb/venn_generic.html
- webapp/views/analysis_view_metadata.py
- webapp/views/entry_lists.py
- webapp/views/gwas.py
- webapp/views/hits_extraction.py
- webapp/views/locus.py
- webapp/views/mixins.py
- webapp/views/object_type_metadata.py
- webapp/views/tabular_comparison.py
- webapp/views/utils.py
- webapp/views/venn.py
- webapp/views/views.py
This gives consistency in naming and descriptions of the different analysis views in different places in the software. It also allows to decrease code duplication, notably by introducing a template for the header section of the analysis views.
We do some clean-up of the templates and fix an issue with the legend in the KO barchart view.
> Consistently use metadata objects in various views.

- bin/zdb
Seems I forgot to commit this in the PR adding the VF filtering feature...
> Add command line variables for filtering VFs to bin/zdb.

- docs/CHANGELOG.md
- testing/webapp/test_download_sequences.py
- testing/webapp/test_views.py
- webapp/chlamdb/urls.py
- webapp/templates/chlamdb/homologs.html
- webapp/views/locus.py
With this PR we add two new buttons in the homologs table allowing to download the protein or DNA sequences for the selected loci.
> Add buttons to download protein and DNA sequences in homologs tables.

- docs/CHANGELOG.md
- testing/webapp/test_views.py
- webapp/assets/js/cookie.js
- webapp/assets/js/custom_plot.js
- webapp/assets/js/jquery.redirect.js
- webapp/templates/chlamdb/extract_hits.html
- webapp/templates/chlamdb/extract_hits_results_table.html
- webapp/templates/chlamdb/homologs.html
- webapp/templates/chlamdb/module_comp.html
- webapp/templates/chlamdb/result_table.html
- webapp/templates/chlamdb/tabular_comparison.html
- webapp/views/custom_plots.py
- webapp/views/gwas.py
- webapp/views/hits_extraction.py
- webapp/views/tabular_comparison.py
- webapp/views/utils.py
With this PR we add a new button to all relevant tables allowing to create a custom phylogeny plot directly from a selection of entries. Note that clicking the button will send you to the custom plots view, with the plot already made but also the form prefilled, allowing you to modify the form and resubmit it.
See screen recording below as an example.
https://github.com/metagenlab/zDB/assets/7374243/424a01ee-ea10-4a47-8cb4-f54ab5cf76b9
> Add button to draw custom phylogeny from selection of entries in various tables.

- webapp/views/analysis_view_metadata.py
I also add spaces around "/" so that it can be split on two lines
> Fix typo in accumulation rarefaction plot metadata.

- docs/CHANGELOG.md
- webapp/templates/chlamdb/locus.html
I added a new card with the actions to the locus overview. I'll add links to blast the protein and DNA sequences in a further PR.
> Integrate link to paper blast in the locus overview.

- docs/CHANGELOG.md
- webapp/templates/chlamdb/locus.html
_Describe the changes and add screenshots when pertinent as visual help._
> Add button to blast protein sequence in the locus overview.

- docs/CHANGELOG.md
- webapp/templates/chlamdb/fam.html
- webapp/templates/chlamdb/home.html
- webapp/views/utils.py
I also updated the links to the Pfam website, as it is now hosted on InterPro.
Resolves https://github.com/metagenlab/zDB/issues/97
> Fix Pfam identifiers

- docs/CHANGELOG.md
- webapp/views/views.py
We also fix blast view for hits with identifier containing a version number.
Resolves https://github.com/metagenlab/zDB/issues/95
> Execute tblastn search against the fna (contigs) database.

- webapp/assets/bibliography/references.bib
> Update scoary2 reference and add paperBLAST to list of references

- README.md
> Fix displying workflows in README.

- CHANGELOG.md
- annotation_pipeline.nf
> Fix amrfinder database update for Linux.

- CHANGELOG.md
- conda/checkm.yaml
The checkm version we were using was not compatible with numpy 2.0 (https://github.com/Ecogenomics/CheckM/issues/397)
> Fix conda checkm environment.

- CHANGELOG.md
- README.md
- bin/zdb
- nextflow.config
With this PR we update the containers for zDB v1.3.0
> Update containers for new zDB release v 1.3.0

- README.md
> Fix displaying zDB workflow images in sphinx documentation.

- CHANGELOG.md
- README.md
_Describe the changes and add screenshots when pertinent as visual help._
> Prepare release 1.3.3

- README.md
> Add update of documentation when making a release to README.

- CHANGELOG.md
- webapp/templates/chlamdb/plot_region.html
- webapp/views/views.py
> Add contig accession and range to genomic regions in plot_region.

- CHANGELOG.md
- webapp/lib/db_utils.py
- webapp/templates/chlamdb/locus.html
- webapp/views/locus.py
We add information about the contig on the locusx view. This notably allows to see whether the gene is on a plasmid and whether that contig is circular or not.
> Add contig card to locusx view.

- CHANGELOG.md
- README.md
- bin/zdb
- db_setup.nf
- nextflow.config
- utils/export_loci_annotations.py
- utils/setup_base_db.py
Having the SQL database stored in the git repository is not ideal. This is not necessary anymore since the setup of the database was sped up (https://github.com/metagenlab/zDB/pull/53).
> Remove zDB's base database and add option to create it with the "zdb setup" command

- CHANGELOG.md
- bin/zdb
- conda/recipe/meta.yaml
- nextflow.config
- testing/conda/test_environments.py
There is no need to use mamba anymore, as conda has integrated mamba's environment solver.
> Use conda instead of mamba for environment creation.

- README.md
- testing/conda/test_environments.py
- testing/pipelines/test_annotation_pipeline.py
- testing/pipelines/test_db_setup.py
- testing/webapp/test_views.py
- webapp/templates/chlamdb/home.html
We add tests for genomic island prediction and visualization. We also add a test for the setup of the base DB.
> Add tests for genomic islands and base DB setup.

- CHANGELOG.md
- annotation_pipeline.nf
- bin/setup_chlamdb.py
- conda/mcl.yaml
- conda/sourmash.yaml
- nextflow.config
- webapp/lib/db_utils.py
With this PR we:
- improve genomic island prediction by adding a blast consistency step (we blast GI sequences found by IslandPath on all genomes and annotate all good hits as GIs)
- identify GI clusters. This is done using sourmash to compare all identified GIs with each other, and then using MCL to determine clusters.
> Add genomic island prediction consistency and clustering to analysis pipeline.

- bin/setup_chlamdb.py
- webapp/lib/db_utils.py
- webapp/lib/queries.py
- webapp/views/fam.py
- webapp/views/genomic_island.py
We now correctly handle genomic islands spanning the edge of circular contigs (hopefully) everywhere.
No changelog entry for this, as GIs have not been released yet.
> Handle genomic islands spanning the boundary of a circular contig

- testing/webapp/test_views.py
- webapp/lib/db_utils.py
- webapp/views/utils.py
No changelog entry, as GIS are not released yet.
> Handle genomic island clusters in custom plots.

- annotation_pipeline.nf
- bin/annotations.py
- bin/setup_chlamdb.py
With this PR we fix the prediction of genomic islands by splitting the genomes into individual contigs before running islandpath, as it does not support multi-contig genomes.
We also fix the check for overlapping GIs and make the GI clusters more fine-grained.
> Fix/improve GI and GI cluster prediction. 

- CHANGELOG.md
- utils/export_loci_mapping.py
@TKlamydionaut can you check whether this script does what you want?
You can run it in the "webapp" conda environment with something like `python utils/export_loci_mapping.py zdb/results/db/voluminous_hamilton 7 14 15 16`
> Add script to export a loci map between genomes.

- webapp/views/fam.py
No changelog entry as this fixes a bug introduced in the same release.
> Fix fam view for genomic island clusters without any AMR or VF hits.

- CHANGELOG.md
- README.md
- webapp/views/fam.py
- webapp/views/genomic_island.py
In the GI genomic region display, a gene which was both annotated
as AMR and VF gene was colored as a VF gene. It will now get colored
as an AMR gene instead.
>  Color genes as AMR if they are annotated as both AMR and VF. 

- CHANGELOG.md
- webapp/lib/db_utils.py
- webapp/views/hits_extraction.py
The presence fraction was wrong in the extraction views as it used a wrong number for the number of genomes.
> Fix presence in DB column in hit extraction view.

- CHANGELOG.md
- webapp/assets/js/blaster.min.js
- webapp/assets/js/html2canvas.js
- webapp/assets/js/jquery.hottie.js
- webapp/templates/chlamdb/error.html
- webapp/templates/chlamdb/extract_hits_cog_barcharts.html
- webapp/templates/chlamdb/menu.html
- webapp/templates/chlamdb/pan_genome.html
- webapp/templates/chlamdb/plot_heatmap.html
- webapp/templates/chlamdb/tabular_comparison.html
- webapp/templates/chlamdb/venn_generic.html
In commit https://github.com/metagenlab/zDB/commit/fd5e3a68576383a60621df177e855aa3e41f7024 I cleaned-up the javascript libraries, but accidentally removed two files that are actually used in zDB. We re-add them here.
We also remove some `console.log` statements which are just polluting the console.
Finally we fix several small things raising errors in the javescript, typically avoid trying to do something with objects that are undefined because they only exist when we have results (the form was posted).
> Re-add JS libraries accidentally removed and fix various small JS errors.

- CHANGELOG.md
- webapp/templates/chlamdb/circos.html
This improves reactivity of the view quite a bit without much loss of information.
> Use larger step for GC content and skew in circos map.
